const {SmartInterval} = require ('smart_interval')
const si = new SmartInterval()
si.add('s',250,_=>{})
si.remove('s')
si.add('s',250,_=>{})
si.remove('s')
si.add('s',250,_=>{})
si.remove('s')
si.add('f',418)
si.add('q',250,_=>{})
si.status()
si.remove('s')
si.remove('q')
si.status()
si.add('q',250,_=>{})
si.add('m',232,_=>{console.log('')})
si.add('w',282,_=>{console.log('')})
si.add('k',141,_=>{console.log('')})
si.status()

si.stopAllIntervals()
si.status()


